### ISSUE TITLE
Access request 

### ISSUE THREAD

**Issue by jriga** [ministryofjustice/github-collaborators#97]
## Which MoJ repository are you requesting access to (e.g. `money-to-prisoners`)?

- tax-tribunals-datacapture
- mojfile-uploader
- tax-tribunals-downloader

## What is the GitHub username of the person who needs access?

jriga

## What is their full name?

Jerome Riga

jerome.riga@hmcts.net

## What company/organisation do they belong to (e.g. "MadeTech", "Department for Education")?

HMCTS

## What level of access should they have?

- [ ] Read
- [ ] Triage
- [ ] Write
- [x] Maintain
- [] Admin

## Why is this access being requested?

Project maintainer

## Which MoJ team/person is responsible for this request?

HMCTS Product Enhancement Team 
"Sunil Parmar"  Sunil.Parmar@HMCTS.NET

## Review date

2021-06-01

**Comment by AntonyBishop** [comment]
Acknowledged

**Comment by AntonyBishop** [comment]
Create PRs for changes. Awaiting approval

**Comment by jriga** [comment]
Hello @AntonyBishop, Since I've been added to these 3 repos, I keep have to re-accept the invitation for tax-tribunals-datacapture and mojfile-uploader every now and then.
I would have expected not to have to regularly have to re-accept the invite. What should I do to acheive that?

**Comment by AntonyBishop** [comment]
Hi @jriga . This should not be happening.

@digitalronin here is another example of someone having to be invited back to the repo. Any ideas? Does this help us build up a picture? 

I note that `permission   = "maintain"`. I know we have an issue with `Write/Push`. Could that be an issue? Or is this something outside of our control?

**Comment by AntonyBishop** [comment]
Will reopen this issue for investigation.

**Comment by digitalronin** [comment]
@jriga @AntonyBishop I'm going to try [this](https://github.com/ministryofjustice/github-collaborators/issues/106#issuecomment-776460806) with these repositories too.

@jriga please accept the new collaboration invitations ASAP - my current theory is that this happens if pending invitations (which don't show up in the API) persist across multiple `terraform apply` steps, although I haven't confirmed that yet).

**Comment by digitalronin** [comment]
@jriga I've found the problem here - it turns out "maintain" and "triage" permissions won't work because of a bug in the GitHub API (see #117 for more info).

I've changed your collaboration permission on those repos to "push" ("admin" would work, too), so as soon as you accept the latest invites, everything should be good.

**Comment by jriga** [comment]
thanks
